### ISSUE TITLE
Fail to discover instance 

### ISSUE THREAD

**Issue by james-shang** [strahlex/MachinekitClient#2]
It fail to discover instance on build: machinekit-client_v0.9.3-28_windows_x86.zip/ machinekit-client_v0.9.3-28_windows_x86.zip / machinekit-client_v0.9.3-7_android_armv7.apk

but It can discover the instance and show cetus with google play store android version on date 3 July.

how can I trace the discover path?

thanks

**Comment by machinekoder** [comment]
You need to update your config to use mklauncher:
https://github.com/strahlex/QtQuickVcp/wiki/Using-mklauncher

Should take you only a few minutes.

james-shang writes:

> It fail to discover instance on build: machinekit-client_v0.9.3-28_windows_x86.zip/ machinekit-client_v0.9.3-28_windows_x86.zip / machinekit-client_v0.9.3-7_android_armv7.apk
> 
> but It can discover the instance and show cetus with google play store android version on date 3 July.
> 
> how can I trace the discover path?
> 
> thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/strahlex/MachinekitClient/issues/2

## 

Alexander

**Comment by james-shang** [comment]
it works.
thank you!
