### ISSUE TITLE
Quickstart button for specified instance and interface

### ISSUE THREAD

**Issue by oeway** [strahlex/MachinekitClient#3]
Hi Alexander,

This is not a bug but feature request.
During the usage of machinekit client, I am thinking maybe the "wizard" method to start an interface for a specified printer is not straightforward. In my opinion, it's good to put the wizard method to setup a machine and the corresponding interface, but after it's done, there should be some shortcut or launch button to start the specified interface. There are many ways to implement something like this, for example, start an home page with customisable launch button, or accept arguments (ip, interface etc.) for startup directly.

What will you say about this?

Best,
Will

**Comment by machinekoder** [comment]
There is a way to do this it is just not documented. You can pass a .json file to the machinekit-client containing the application and selection settings. However, this is the way a manufacturer could prepare machinekit-client. A user-friendly way to select a favorite is a good idea.

**Comment by oeway** [comment]
Hi, could you please give an example of the content of the json file?

On Sat, Sep 12, 2015 at 8:56 PM, Alexander Rössler <notifications@github.com

**Comment by machinekoder** [comment]
For example

``` json
{
    "autoSelectInstance": true,
    "autoSelectApplication": true,
    "lookupMode": 1,
    "mode": "remote",
    "nameServers": [
        {
            "hostName": "192.168.7.2",
            "port": 5353
        }
    ]
}
```

run MachinekitClient like `machinekit-client --config bbb.json`

**Comment by oeway** [comment]
Thanks very much.

On Sun, Sep 13, 2015 at 5:00 AM, Alexander Rössler <notifications@github.com

**Comment by machinekoder** [comment]
MachinekitClient has moved
