### ISSUE TITLE
Different number of services: Android vs. Windows

### ISSUE THREAD

**Issue by sirop** [strahlex/MachinekitClient#6]
I do not know if it is a bug or a feature but it is at least worth clarification.

Machinekit kit runs on debian wheezy.
I start `mklauncher mkwrapper-sim/` .

Then start MachinekitClient on Windows 8.1:

![machinekitclient_win_services](https://cloud.githubusercontent.com/assets/1533811/13555078/b3f8301e-e3b7-11e5-9062-b1f80996b44d.png)

Stop MachinekitClient on Windows. Start MachinekitClient on Android:

![machinekitclient_android_services](https://cloud.githubusercontent.com/assets/1533811/13555091/deb90cf6-e3b7-11e5-965f-73f82cbbac9b.png)

The connection runs in both cases over WiFi with my home router inbetween.

http://buildbot.roessler.systems/files/machinekit-client/machinekit-client_v0.9.6-3-g75cd-126_windows_x86.zip used on Windows.  

http://buildbot.roessler.systems/files/machinekit-client/machinekit-client_v0.9.6-3-g75cd-71_android_armv7.apk used on Android 4.4.2 .

Device: Samsung C115

**Comment by sirop** [comment]
Looked further into it: I got the above Android screenshot in Multicast mode.

If I make my Android device use the Unicast mode, it shows the same services
as on windows where only Unicast mode sets up the connection - at least in my case.

**Comment by machinekoder** [comment]
This is the correct behavior. Unicast most only queries the services required by the application.

Have you tried https://github.com/strahlex/querierd ? Maybe it will make Multicast mode also work on Windows.
