### ISSUE TITLE
random segfaults

### ISSUE THREAD

**Issue by koppi** [strahlex/MachinekitClient#7]
I often see a random segfaults:

``` bash
/opt/machinekit-client/machinekit-client: line 13: 20454 Segmentation fault      /lib64/ld-linux-x86-64.so.2 "$CWD"/bin/machinekit-client $@
```

@strahlex can you provide binaries of MachinekitClient with debugging information enabled?

**Comment by machinekoder** [comment]
Not easily. However, the segfaults are usually related to the 3D preview. Can you confirm this?

**Comment by koppi** [comment]
I did not compile MachinekitClient from source with debugging information enabled, so I do not know, where / why / when this happens.
