### ISSUE TITLE
Low FPS on Ubuntu 16.04

### ISSUE THREAD

**Issue by koppi** [strahlex/MachinekitClient#8]
On Ubuntu 16.04 the OpenGL preview has a very low (maybe 0.5) frames per second number with a moderate big ngc file, see [video](https://www.youtube.com/watch?v=bqeekd1NO1A). @strahlex can you reproduce this issue on other platforms Windows / Mac?

**Comment by machinekoder** [comment]
Yes, performance is low in general. Needs re-implementation with Qt3D http://doc.qt.io/qt-5/qt3d-index.html

**Comment by machinekoder** [comment]
MachinekitClient has moved
